# Generated by Django 4.2.5 on 2023-09-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycloakuser',
            name='createdTimestamp',
            field=models.IntegerField(),
        ),
    ]
