# Generated by Django 4.2.5 on 2023-09-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_alter_keycloakuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycloakuser',
            name='createdTimestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
