# Generated by Django 4.2.5 on 2023-10-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_alter_keycloakuser_createdtimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='keycloakuser',
            name='password',
            field=models.CharField(default='tcs123', max_length=100),
            preserve_default=False,
        ),
    ]
