# Generated by Django 4.2.5 on 2023-10-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0007_alter_keycloakuser_attributes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keycloakuser',
            old_name='attributes',
            new_name='attribute',
        ),
    ]
