# Generated by Django 4.2.5 on 2023-10-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0008_rename_attributes_keycloakuser_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keycloakuser',
            name='attribute',
        ),
    ]
